name: minify
run-name: Mififying JS
on: [push]

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          overwrite: true
          directory: 'js'
          js_engine: 'babel'

      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}
